// Prove di veritas_bim.js — l'IFC come ingresso di prima classe.
//
//     node veritas_bim.test.mjs
//
// DUE LIVELLI, ed e' voluto:
//
//   1. la LOGICA PURA (nomi, vocabolario, collegamenti, misure) provata su
//      dati scritti a mano qui dentro: gira sempre, anche senza web-ifc;
//   2. la LETTURA VERA su `banco/finti/casa_finta.ifc`, un IFC scritto a mano
//      riga per riga, letto con web-ifc — il lettore vero, non una copia. Se
//      web-ifc non e' installato queste prove si dichiarano saltate invece di
//      fallire, cosi' il banco resta verde su una macchina senza npm install.
//
// ⚠️ La casa di prova NON e' il modello di nessuno: e' inventata perche' ogni
// caso che deve funzionare sia visibile a occhio nudo dentro il file. Le
// misure prese sul modello ArchiCAD pubblico (AC20-FZK-Haus) stanno nei
// commenti di veritas_bim.js, non qui: una prova che gira solo se hai
// scaricato un file da internet non e' una prova.

import fs from "node:fs";
import {
  eIfc, intestazione, testoDi, numeroDi, booleanoDi,
  nomeDiSpazio, nomeDiPiano, funzioneDaNome, VOCABOLARIO_SPAZI, TIPO_DA_FUNZIONE,
  collegamentiDaBordi, isole, datiDaProprieta, zoneDaSpazi, misuraVolume,
  grafoCamminabile, stanzaDelPunto, percorsoDichiarato, confineFra,
  leggi, riassunto,
} from "./veritas_bim.js";

let fatte = 0, rotte = 0, saltate = 0;
function ok(cond, che) {
  fatte++;
  if (cond) console.log("  ok   " + che);
  else { rotte++; console.log("  ROTTO " + che); }
}
function uguale(a, b, che) { ok(a === b, `${che}  (${JSON.stringify(a)})`); }
function vicino(a, b, tol, che) {
  ok(typeof a === "number" && Math.abs(a - b) <= tol, `${che}  (${a} atteso ~${b})`);
}
const byte = (s) => new Uint8Array([...s].map((c) => c.charCodeAt(0)));

// ===========================================================================
console.log("\n=== 1. riconoscimento: un IFC si riconosce dai byte ===");
// ===========================================================================
ok(eIfc(byte("ISO-10303-21;\nHEADER;")), "l'intestazione ISO-10303-21 e' un IFC");
// Il BOM di UTF-8 e' una sequenza di TRE BYTE, non un carattere: un editor
// Windows ce lo mette, e va tolto sui byte o il file risulta sconosciuto.
ok(eIfc(new Uint8Array([0xEF, 0xBB, 0xBF, ...byte("ISO-10303-21;")])),
  "un BOM di UTF-8 davanti non lo nasconde");
ok(eIfc(byte("\n\n  ISO-10303-21;")), "righe vuote davanti non lo nascondono");
ok(!eIfc(byte("glTF\0\0\0")), "un glb NON e' un IFC");
ok(!eIfc(byte("ply\nformat ascii 1.0")), "un ply NON e' un IFC");
ok(!eIfc(new Uint8Array(0)), "zero byte non sono un IFC");

const intest = intestazione(byte(
  "ISO-10303-21;\nHEADER;\nFILE_NAME('a.ifc','2016-12-21T17:54:06',('Architect'),('Studio'),"
  + "'EDM 5.02','IFC file generated by GRAPHISOFT ARCHICAD-64 20.0.0 GER FULL Windows version',''); \n"
  + "FILE_SCHEMA(('IFC4'));\n"));
uguale(intest.schema, "IFC4", "lo schema si legge dall'intestazione");
ok(/ARCHICAD/.test(intest.applicazione || ""), "chi ha esportato si legge dall'intestazione");
// Un IFC puo' avere righe di commento in cima. Cercando il programma in tutta
// l'intestazione si finisce per leggere un commento: successo davvero, il
// 19/08, sul file di prova di questo modulo.
const conCommento = intestazione(byte(
  "ISO-10303-21;\nHEADER;\n/* attenzione alla trappola ARCHICAD: il nome sta in LongName */\n"
  + "FILE_NAME('a.ifc','2026-01-01',(''),(''),'','IfcOpenShell 0.7.0','');\nFILE_SCHEMA(('IFC4'));\n"));
ok(/IfcOpenShell/.test(conCommento.applicazione || ""),
  "un commento che nomina un programma non viene scambiato per il programma");

// ===========================================================================
console.log("\n=== 2. srotolare i valori di web-ifc ===");
// ===========================================================================
uguale(testoDi({ value: "Flur", type: 1, name: "IFCLABEL" }), "Flur", "una stringa");
uguale(testoDi({ type: 3, value: "INTERNAL" }), "INTERNAL", "un enumerato");
uguale(testoDi({ _internalValue: "120.", _representationValue: 120 }), "120",
  "una misura, che NON ha .value — e' la forma che fa sbagliare");
uguale(testoDi(null), null, "null resta null");
uguale(testoDi({ value: "   " }), null, "una stringa di soli spazi vale null");
uguale(numeroDi({ _representationValue: 120 }), 120, "il numero di una misura");
uguale(numeroDi({ value: "non un numero" }), null, "testo non numerico -> null");
uguale(booleanoDi({ value: true }), true, "un booleano vero");
uguale(booleanoDi({ value: "F" }), false, "la forma .F. di STEP");
uguale(booleanoDi({ value: "forse" }), null, "quello che non e' un booleano -> null");

// ===========================================================================
console.log("\n=== 3. LA TRAPPOLA ARCHICAD: il nome sta in LongName ===");
// ===========================================================================
const zona = { Name: { value: "101" }, LongName: { value: "Sala d'attesa" } };
uguale(nomeDiSpazio(zona).nome, "Sala d'attesa", "il NOME viene da LongName");
uguale(nomeDiSpazio(zona).numero, "101", "e Name resta il NUMERO della stanza");
ok(nomeDiSpazio(zona).dichiarato === true, "e' un nome dichiarato");

const soloNumero = { Name: { value: "103" }, LongName: null };
uguale(soloNumero.LongName, null, "(caso: LongName assente)");
uguale(nomeDiSpazio(soloNumero).nome, null,
  "senza LongName NON si inventa un nome: resta null");
uguale(nomeDiSpazio(soloNumero).numero, "103", "il numero si conserva");
ok(nomeDiSpazio(soloNumero).dichiarato === false,
  "e si dichiara che nessuno ha descritto questa stanza");

const nomeInName = { Name: { value: "Ufficio 2" }, LongName: null };
uguale(nomeDiSpazio(nomeInName).nome, "Ufficio 2",
  "se pero' Name contiene lettere, qualcuno l'ha scritto e vale");

uguale(nomeDiSpazio({}).nome, null, "una riga vuota non fa cadere niente");

// ⚠️ Per i PIANI la regola e' rovesciata, ed e' un difetto misurato sul file
// ArchiCAD vero: Name='Erdgeschoss', LongName='ACID00000001-0000-…'.
uguale(nomeDiPiano({ Name: { value: "Erdgeschoss" }, LongName: { value: "ACID00000001-0000-0000-0000-000000000000" } }),
  "Erdgeschoss", "il nome di un PIANO sta in Name, non in LongName");
uguale(nomeDiPiano({ Name: null, LongName: { value: "Piano primo" } }), "Piano primo",
  "se Name manca si usa LongName");
uguale(nomeDiPiano({ Name: { value: "ACID00000002-0000-0000-0000-000000000000" }, LongName: { value: "Dachgeschoss" } }),
  "Dachgeschoss", "un identificativo interno non e' un nome, da qualunque parte arrivi");
uguale(nomeDiPiano({}), null, "un piano senza nome non ne riceve uno inventato");

// ===========================================================================
console.log("\n=== 4. il vocabolario legge una parola scritta, non una forma ===");
// ===========================================================================
uguale(funzioneDaNome("Sala d'attesa"), "attesa", "italiano");
uguale(funzioneDaNome("Waiting area"), "attesa", "inglese");
uguale(funzioneDaNome("Flur"), "corridoio", "tedesco (il modello ArchiCAD pubblico e' tedesco)");
uguale(funzioneDaNome("Schlafzimmer"), "camera", "tedesco, camera");
uguale(funzioneDaNome("Gate A12"), "destinazione", "un gate");
uguale(funzioneDaNome("Controllo sicurezza"), "controlli", "il filtro");
uguale(funzioneDaNome("Locale tecnico"), "tecnico", "un locale tecnico");
uguale(funzioneDaNome("Sala espositiva 2"), "esposizione", "una sala di museo");
uguale(funzioneDaNome("Zona 4"), null,
  "un nome che non dice niente NON riceve una funzione plausibile: resta null");
uguale(funzioneDaNome(null), null, "nessun nome, nessuna funzione");
// La parola piu' lunga vince: e' il difetto che farebbe diventare
// "sala d'attesa" una sala espositiva, perche' contiene "sala".
uguale(funzioneDaNome("SALA D'ATTESA"), "attesa", "vince la parola piu' lunga, e non conta il maiuscolo");
ok(TIPO_DA_FUNZIONE.tecnico.escluso === true,
  "un locale tecnico non e' una tappa di un percorso pubblico");
// Difetti trovati sul modello ArchiCAD vero il 19/08, e chiusi. Nessuno dei
// due dava un errore: si vedono solo guardando l'uscita.
uguale(funzioneDaNome("Buero"), "ufficio",
  "un ufficio NON e' un locale tecnico (sul file vero usciva escluso dal percorso)");
ok(TIPO_DA_FUNZIONE.ufficio.escluso !== true, "e quindi resta nel percorso");
uguale(funzioneDaNome("Kueche"), "cucina",
  "una cucina NON e' un'area commerciale (sul file vero usciva cosi')");
ok(TIPO_DA_FUNZIONE.cucina.escluso !== true, "e resta nel percorso");
ok(TIPO_DA_FUNZIONE.servizi.escluso === true, "e nemmeno un bagno");
ok(TIPO_DA_FUNZIONE.ingresso.tipo === "spawn" && TIPO_DA_FUNZIONE.destinazione.tipo === "gate",
  "il vocabolario dei type portanti non e' cambiato");
for (const f in VOCABOLARIO_SPAZI) {
  if (!TIPO_DA_FUNZIONE[f]) ok(false, "la funzione " + f + " non ha un tipo");
}
ok(true, "ogni funzione del vocabolario ha un tipo corrispondente");

// ===========================================================================
console.log("\n=== 5. IL MURO NON E' UN PASSAGGIO (la trappola numero due) ===");
// ===========================================================================
const bordi = [
  { spazio: 100, elemento: 10, tipoElemento: "IFCDOOR", nomeElemento: "Porta interna", larghezzaM: 0.9 },
  { spazio: 101, elemento: 10, tipoElemento: "IFCDOOR", nomeElemento: "Porta interna", larghezzaM: 0.9 },
  { spazio: 100, elemento: 11, tipoElemento: "IFCWALL", nomeElemento: "Muro divisorio" },
  { spazio: 101, elemento: 11, tipoElemento: "IFCWALL", nomeElemento: "Muro divisorio" },
  { spazio: 100, elemento: 12, tipoElemento: "IFCSLAB", nomeElemento: "Solaio" },
  { spazio: 101, elemento: 12, tipoElemento: "IFCSLAB", nomeElemento: "Solaio" },
  { spazio: 100, elemento: 13, tipoElemento: "IFCDOOR", nomeElemento: "Porta d'ingresso", larghezzaM: 1.2 },
];
const r = collegamentiDaBordi(bordi);
uguale(r.collegamenti.length, 1,
  "un muro e un solaio bordano due stanze ma NON le collegano: un solo collegamento");
uguale(r.collegamenti[0].tipo, "porta", "e quel collegamento e' la porta");
vicino(r.collegamenti[0].larghezzaM, 0.9, 0.001, "con la larghezza dichiarata dalla porta");
uguale(r.esterni.length, 1,
  "una porta che borda UN solo ambiente da' sull'esterno: e' un ingresso");
uguale(r.esterni[0].spazio, 100, "e dichiara quale ambiente si entra");

const scale = collegamentiDaBordi([
  { spazio: 1, elemento: 5, tipoElemento: "IFCSTAIR" },
  { spazio: 2, elemento: 5, tipoElemento: "IFCSTAIR" },
  { spazio: 1, elemento: 6, tipoElemento: "IFCVIRTUALELEMENT" },
  { spazio: 3, elemento: 6, tipoElemento: "IFCVIRTUALELEMENT" },
]);
uguale(scale.collegamenti.length, 2, "scale e varchi virtuali collegano");
ok(scale.collegamenti.some((c) => c.tipo === "scala"), "una scala e' un passaggio");
ok(scale.collegamenti.some((c) => c.tipo === "varco"),
  "un varco virtuale e' un passaggio: due ambienti con niente in mezzo");

const tre = collegamentiDaBordi([
  { spazio: 1, elemento: 9, tipoElemento: "IFCDOOR" },
  { spazio: 2, elemento: 9, tipoElemento: "IFCDOOR" },
  { spazio: 3, elemento: 9, tipoElemento: "IFCDOOR" },
]);
uguale(tre.collegamenti.length, 3, "una porta su tre ambienti dichiara tutte e tre le coppie");
uguale(collegamentiDaBordi([]).collegamenti.length, 0, "nessun bordo, nessun collegamento");
uguale(collegamentiDaBordi(null).collegamenti.length, 0, "null non fa cadere niente");

// ===========================================================================
console.log("\n=== 5-bis. CAMMINARE DALLE PORTE, non dentro i muri ===");
// ===========================================================================
// Il difetto che Raffaella ha visto il 20/08: «attraversano i muri e non usano
// le scale». Sapere CHE due stanze comunicano non basta: serve sapere DA DOVE.
// Tre stanze in fila: A -porta a x=5- B -porta a x=15- C
const stanza = (id, x, largo) => ({
  ifc: { id }, pos: [x, 0, 0], label: "S" + id,
  ingombro: { min: [x - largo / 2, 0, -4], max: [x + largo / 2, 3, 4] },
});
const zoneTre = [stanza(1, 0, 10), stanza(2, 10, 10), stanza(3, 20, 10)];
const gr = grafoCamminabile(zoneTre, [
  { da: 1, a: 2, punto: [5, 0, 2], tipo: "porta" },
  { da: 2, a: 3, punto: [15, 0, -2], tipo: "porta" },
]);
uguale(gr.quanti, 2, "due passaggi dichiarati");
uguale(gr.stanze.size, 3, "tre ambienti");

const via = percorsoDichiarato(gr, [-3, 0, 0], [19, 0, 0]);
ok(via && via.length >= 3, "un percorso da A a C esiste");
// ⚠️ la prova che conta: passa DAI DUE PUNTI DELLE PORTE, non in linea retta
ok(via.some((p) => Math.abs(p[0] - 5) < 0.01 && Math.abs(p[2] - 2) < 0.01),
  "il percorso passa dalla PORTA fra A e B, non dal muro");
ok(via.some((p) => Math.abs(p[0] - 15) < 0.01 && Math.abs(p[2] + 2) < 0.01),
  "e dalla porta fra B e C");
const dritto = via.filter((p) => Math.abs(p[2]) < 0.01).length;
ok(dritto < via.length, "quindi NON e' una linea retta");

uguale(percorsoDichiarato(gr, [-3, 0, 0], [-1, 0, 0]).length, 1,
  "dentro la stessa stanza si va dritti, e va bene");

// Una stanza scollegata: non si inventa una strada
const grRotto = grafoCamminabile(zoneTre, [{ da: 1, a: 2, punto: [5, 0, 2] }]);
uguale(percorsoDichiarato(grRotto, [-3, 0, 0], [19, 0, 0]), null,
  "se il file non dichiara una strada, si risponde NULL invece di una retta nel muro");

// La scala: due ambienti a quote diverse, collegati da una scala dichiarata
const sopra = { ifc: { id: 9 }, pos: [0, 2.7, 0], label: "Galleria",
                ingombro: { min: [-5, 2.7, -4], max: [5, 5.4, 4] } };
const conScala = grafoCamminabile([zoneTre[0], sopra], [
  { da: 1, a: 9, punto: [2, 0, 3], tipo: "scala" },
]);
const salita = percorsoDichiarato(conScala, [-3, 0, 0], [0, 2.7, 0]);
ok(salita && salita.some((p) => Math.abs(p[1]) < 0.01) && salita.some((p) => p[1] > 2),
  "per salire di piano il percorso passa dalla SCALA dichiarata, non buca il solaio");

// Il varco aperto: nel file non ha geometria, e il punto si ricava dal confine
// dichiarato fra i due volumi. Senza questo, meta' di una casa moderna resta
// scollegata (misurato su AC20-FZK-Haus: 3 varchi virtuali su 6 passaggi).
const aperto = grafoCamminabile(zoneTre, [{ da: 1, a: 2, punto: null, tipo: "varco" }]);
uguale(aperto.quanti, 1, "un varco senza geometria resta percorribile");
const c1 = confineFra(zoneTre[0], zoneTre[1]);
ok(c1 && Math.abs(c1[0] - 5) < 0.01, "il punto e' dove i due volumi si affacciano");
uguale(confineFra(zoneTre[0], zoneTre[2]), null,
  "due stanze che non si toccano non ricevono un punto inventato");

uguale(stanzaDelPunto(gr, [0, 0, 0]), 1, "un punto dentro una stanza sa in quale sta");
uguale(stanzaDelPunto(gr, [500, 0, 500]), null, "un punto lontano da tutto non appartiene a nessuna");
uguale(percorsoDichiarato({ quanti: 0 }, [0, 0, 0], [1, 0, 0]), null,
  "senza grafo, nessun percorso dichiarato");

// ===========================================================================
console.log("\n=== 6. le isole: cosa non si raggiunge, dichiarato ===");
// ===========================================================================
const g = isole([1, 2, 3, 4, 5], [{ da: 1, a: 2 }, { da: 2, a: 3 }]);
uguale(g.length, 3, "tre gruppi: {1,2,3}, {4}, {5}");
uguale(g[0].length, 3, "il primo e' il piu' grande");
uguale(isole([1, 2], []).length, 2, "senza collegamenti ogni ambiente e' un'isola");
uguale(isole([1, 2, 3], [{ da: 1, a: 9 }])[0].length, 1,
  "un collegamento verso un ambiente che non esiste non unisce niente");

// ===========================================================================
console.log("\n=== 7. i dati dichiarati per le normative ===");
// ===========================================================================
const d = datiDaProprieta([
  { id: 1, nome: "A", proprieta: { OccupancyNumber: 120, HandicapAccessible: true } },
  { id: 2, nome: "B", proprieta: { OccupancyNumber: 40, FireRating: "REI 60" } },
  { id: 3, nome: "C", proprieta: {} },
]);
uguale(d.affollamento, 160, "l'affollamento e' la somma di quello dichiarato stanza per stanza");
uguale(d.daSpazi, 2, "e si dice su quanti ambienti e' dichiarato");
uguale(d.accessibili, 1, "gli ambienti dichiarati accessibili si contano");
uguale(d.resistenzaAlFuoco.length, 1, "la resistenza al fuoco dichiarata si conserva");
uguale(datiDaProprieta([{ id: 1, proprieta: {} }]).affollamento, null,
  "se NESSUNO lo dichiara resta null, non zero: la verifica deve dire che il dato manca");

// ===========================================================================
console.log("\n=== 8. la misura sul volume dichiarato ===");
// ===========================================================================
// Una scatola 10 x 8 x 3 chiusa, facce in ordine antiorario viste da sopra.
function scatola(lx, ly, lz, ox = 0, oy = 0, oz = 0) {
  const v = [], idx = [];
  const p = [
    [0, 0, 0], [lx, 0, 0], [lx, 0, lz], [0, 0, lz],
    [0, ly, 0], [lx, ly, 0], [lx, ly, lz], [0, ly, lz],
  ].map((q) => [q[0] + ox, q[1] + oy, q[2] + oz]);
  for (const q of p) v.push(q[0], q[1], q[2], 0, 1, 0);
  const facce = [
    [0, 1, 2], [0, 2, 3],   // sotto
    [4, 6, 5], [4, 7, 6],   // sopra
    [0, 4, 5], [0, 5, 1], [1, 5, 6], [1, 6, 2],
    [2, 6, 7], [2, 7, 3], [3, 7, 4], [3, 4, 0],
  ];
  for (const f of facce) idx.push(...f);
  return { v: new Float32Array(v), idx: new Uint32Array(idx) };
}
const s = scatola(10, 3, 8);
const m = misuraVolume(s.v, s.idx, null);
vicino(m.areaM2, 80, 0.01, "una stanza 10 x 8 misura 80 m2 di pavimento");
vicino(m.centro[0], 5, 0.01, "il baricentro in X");
vicino(m.centro[2], 4, 0.01, "il baricentro in Z");
vicino(m.centro[1], 0, 0.01, "la quota e' il PAVIMENTO, non il centro del volume");
vicino(m.ingombro.max[1] - m.ingombro.min[1], 3, 0.01, "l'altezza della stanza");

// La stessa scatola con le facce girate al contrario: e' il difetto che il
// 18/08 sera aveva dato zero poligoni su ogni scena di prova.
const rovescia = { v: s.v, idx: new Uint32Array([...s.idx].reverse()) };
const mr = misuraVolume(rovescia.v, rovescia.idx, null);
vicino(mr.areaM2, 80, 0.01, "e la misura regge anche con le facce orientate al contrario");

// Una matrice che trasla di (100, 0, 50)
const tras = [1,0,0,0, 0,1,0,0, 0,0,1,0, 100,0,50,1];
const mt = misuraVolume(s.v, s.idx, tras);
vicino(mt.centro[0], 105, 0.01, "la trasformazione dichiarata sposta il baricentro");
vicino(mt.areaM2, 80, 0.01, "ma non ne cambia l'area");

// ===========================================================================
console.log("\n=== 9. da spazi dichiarati a zone VERITAS ===");
// ===========================================================================
const zone = zoneDaSpazi([
  { id: 1, guid: "g1", nome: "Atrio", numero: "1", centro: [0, 0, 0], areaM2: 50, piano: "Terra" },
  { id: 2, guid: "g2", nome: "Sala d'attesa", numero: "2", centro: [10, 0, 0], areaM2: 120, piano: "Terra" },
  { id: 3, guid: "g3", nome: null, numero: "3", centro: [20, 0, 0], areaM2: 16, piano: "Terra" },
  { id: 4, guid: "g4", nome: "Locale tecnico", numero: "4", centro: [30, 0, 0], areaM2: 8, piano: "Terra" },
  { id: 5, guid: "g5", nome: "Senza volume", numero: "5", centro: null, areaM2: null, piano: "Terra" },
], { esterni: [1] });

uguale(zone.length, 4, "un ambiente senza volume non diventa una tappa");
uguale(zone[0].label, "Atrio", "l'etichetta e' il nome SCRITTO NEL FILE");
uguale(zone[0].origine, "bim", "e la provenienza e' dichiarata su ogni zona");
uguale(zone[0].type, "spawn", "l'atrio, che ha una porta verso l'esterno, e' l'ingresso");
ok(zone[0].confermata === true, "una zona con un nome dichiarato nasce confermata");
uguale(zone[1].type, "lounge", "la sala d'attesa e' una sosta");
uguale(zone[2].label, "Ambiente 3", "una stanza senza nome mostra il suo numero");
ok(zone[2].confermata === false,
  "e NON nasce confermata: e' esattamente il caso in cui bisogna chiedere");
ok(zone[2].fiducia < 1, "con fiducia piu' bassa");
ok(zone[3].escluso === true, "il locale tecnico resta nel referto ma fuori dal percorso");
uguale(zone[0].ifc.numero, "1", "il numero della stanza resta consultabile");

const omonime = zoneDaSpazi([
  { id: 1, nome: "Ufficio", numero: "12", centro: [0, 0, 0] },
  { id: 2, nome: "Ufficio", numero: "13", centro: [5, 0, 0] },
  { id: 3, nome: "Corridoio", numero: "14", centro: [9, 0, 0] },
], {});
ok(omonime[0].label !== omonime[1].label, "due stanze non si chiamano mai uguale");
ok(omonime[0].label.includes("12") && omonime[1].label.includes("13"),
  "e si distinguono col NUMERO scritto nel file, non con un contatore inventato");
uguale(omonime[2].label, "Corridoio", "chi era gia' unico non viene toccato");

// ===========================================================================
console.log("\n=== 10. LA LETTURA VERA, con web-ifc, su un IFC scritto a mano ===");
// ===========================================================================
let WebIFC = null;
try { WebIFC = await import("web-ifc"); }
catch (e) { WebIFC = null; }

const percorso = new URL("./banco/finti/casa_finta.ifc", import.meta.url);
if (!WebIFC) {
  saltate++;
  console.log("  SALTATE — web-ifc non installato (npm install web-ifc@0.0.77)");
} else if (!fs.existsSync(percorso)) {
  saltate++;
  console.log("  SALTATE — manca banco/finti/casa_finta.ifc");
} else {
  const dati = new Uint8Array(fs.readFileSync(percorso));
  ok(eIfc(dati), "il file di prova si riconosce dai byte");

  const esito = await leggi(dati, { webifc: WebIFC, wasm: null, conGeometria: false });

  uguale(esito.schema, "IFC4", "schema letto");
  uguale(esito.conteggi.spazi, 4, "quattro ambienti dichiarati");
  uguale(esito.conteggi.conNome, 3, "tre hanno un nome, uno solo un numero");

  const perNome = new Map(esito.spazi.map((x) => [x.nome, x]));
  ok(perNome.has("Sala d'attesa"), "il nome viene da LongName, non da Name — sul lettore VERO");
  uguale(perNome.get("Sala d'attesa").numero, "101", "e il numero della stanza e' 101");
  ok(esito.spazi.some((x) => x.nome === null && x.numero === "103"),
    "la stanza senza LongName non ha ricevuto un nome inventato");

  // le misure, dai volumi dichiarati nel file: 10x8 = 80, 12x8 = 96, 4x4 = 16
  vicino(perNome.get("Sala d'attesa").areaM2, 80, 0.5, "80 m2 misurati dal volume dichiarato");
  vicino(perNome.get("Gate A").areaM2, 96, 0.5, "96 m2 per il secondo ambiente");
  vicino(perNome.get("Sala d'attesa").centro[0], 5, 0.2, "il baricentro sta dove il file lo mette");

  uguale(esito.conteggi.piani, 1, "un piano");
  uguale(esito.spazi[0].piano, "Piano terra",
    "il nome del piano viene da Name, e l'identificativo interno in LongName viene buttato");

  // il muro c'e', e non deve collegare niente
  uguale(esito.collegamenti.length, 1,
    "un solo collegamento: la porta interna. Il muro borda due stanze e non le collega");
  uguale(esito.collegamenti[0].tipo, "porta", "ed e' una porta");
  uguale(esito.esterni.length, 1, "una porta da' sull'esterno");
  const ingresso = esito.spazi.find((x) => x.id === esito.esterni[0].spazio);
  uguale(ingresso.nome, "Sala d'attesa", "e dichiara da dove si entra");

  // il bordo che punta a un elemento inesistente non fa cadere la lettura
  ok(esito.avvisi.some((a) => /non c'e'/.test(a)),
    "il bordo rotto viene dichiarato invece di far cadere il file");

  // l'affollamento, dichiarato dal progettista
  uguale(esito.dati.affollamento, 160, "l'affollamento dichiarato: 120 + 40");
  uguale(esito.dati.daSpazi, 2, "su due ambienti");

  // le zone che escono. Il «Locale tecnico» nel file e' dichiarato SENZA
  // volume: esiste e ha un nome, ma nessuno ha detto dove sta. Non diventa una
  // tappa, e la cosa viene detta invece che taciuta.
  const perEtichetta = new Map(esito.zone.map((z) => [z.label, z]));
  uguale(esito.zone.length, 3, "tre zone: l'ambiente senza volume non ne diventa una");
  ok(!perEtichetta.has("Locale tecnico"),
    "l'ambiente senza volume resta fuori dalle tappe");
  ok(esito.spazi.some((x) => x.nome === "Locale tecnico"),
    "ma resta negli ambienti letti, perche' il file lo dichiara");
  ok(esito.avvisi.some((a) => /senza un volume/.test(a)),
    "e il motivo si legge negli avvisi, non si indovina");
  uguale(perEtichetta.get("Sala d'attesa").type, "spawn",
    "chi ha la porta verso l'esterno e' l'ingresso, comunque si chiami");
  uguale(perEtichetta.get("Gate A").type, "gate", "il gate viene dal nome dichiarato");
  ok(esito.zone.every((z) => z.origine === "bim"), "tutte dichiarano di venire dal BIM");

  // le isole: la stanza 103 e la 104 non comunicano con nessuno
  ok(esito.isole.length > 1, "gli ambienti scollegati sono dichiarati, non usati in silenzio");

  const testo = riassunto(esito);
  ok(/4 ambienti dichiarati/.test(testo), "il racconto dice quanti ambienti ha letto");
  ok(/non li ho dedotti/.test(testo), "e dichiara che i nomi non sono dedotti");

  console.log("\n  --- quello che il file dice, in chiaro ---");
  console.log("  " + testo);
  for (const z of esito.zone) {
    console.log("   ", z.label.padEnd(22), z.type.padEnd(9),
      (z.areaM2 ? z.areaM2.toFixed(1) + " m2" : "—").padStart(9),
      z.confermata ? "confermata" : "DA CONFERMARE");
  }
  for (const a of esito.avvisi) console.log("    avviso:", a);
}

// ===========================================================================
console.log(`\n${fatte} prove, ${rotte} rotte${saltate ? ", " + saltate + " gruppi saltati" : ""}`);
process.exit(rotte ? 1 : 0);
